name: Robô Expedição

on:
  # Permite rodar manualmente pelo GitHub
  workflow_dispatch: {}
  
  # Define um agendamento (a cada hora, no minuto 0)
  schedule:
    - cron: '0 * * * *' 

jobs:
  run-expedicao-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v4

      - name: 2. Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- ETAPA DE DEBUG (Versão Corrigida) ---
      # Esta etapa vai nos mostrar o que está salvo no segredo
      - name: 4a. DEBUG - Mostra o início do segredo
        run: |
          echo "Debug: Verificando o início do segredo..."
          SECRET_PREVIEW=$(echo "${{ secrets.GOOGLE_CREDENTIALS }}" | cut -c1-20)
          echo "O segredo começa com: $SECRET_PREVIEW..."

      - name: 4b. Criar arquivo de credenciais do Google
        # Pega a string Base64, decodifica, e salva o JSON original
        run: printf '%s' "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > credentials.json

      - name: 5. Rodar o Script Python
        # O script agora usará o credentials.json local
        run: python main.py 
        
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SEATALK_WEBHOOK_URL: ${{ secrets.SEATALK_WEBHOOK_URL }}
