name: main

on:
  workflow_dispatch:      # Permite execução manual
  schedule:
    - cron: '*/15 * * * *' # Roda a cada 15 min (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Este passo não é mais necessário, mas não faz mal deixá-lo
      - name: Listar arquivos no repositório
        run: ls -R

      - name: Executar o script
        env:
          GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }} 
          SEATALK_WEBHOOK_URL: ${{ secrets.SEATALK_WEBHOOK_URL }} 
        
        # --- CORREÇÃO AQUI ---
        # Trocamos 'monitor_lts.py' pelo nome correto: 'main.py'
        run: python main.py
