name: main

on:
  workflow_dispatch:      # Permite execução manual
  
  schedule:
    # "Acorda" o script 8 minutos antes da hora cheia e meia hora.
    # (Inicia 18:22, para o script "esperar no portão" até 18:30)
    - cron: '22,52 * * * *' 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Executar o script
        env:
          GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }} 
          SEATALK_WEBHOOK_URL: ${{ secrets.SEATALK_WEBHOOK_URL }} 
        run: python main.py
