name: main

on:
  workflow_dispatch:      # Permite execução manual
  
  # --- BLOCO DE AGENDAMENTO REATIVADO ---
  schedule:
    # Roda exatamente aos 0 e 30 minutos de cada hora (fuso UTC)
    - cron: '0,30 * * * *' 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Listar arquivos (para debug)
        run: ls -R

      - name: Executar o script
        env:
          GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }} 
          SEATALK_WEBHOOK_URL: ${{ secrets.SEATALK_WEBHOOK_URL }} 
        run: python main.py
